const mongoose = require("mongoose");

const usageSchema = new mongoose.Schema({
    treatDate: String,
    secUsed: Number,
    secHumid: Number,
    timePB: Number,
    cntAHI: Number,
    cntOAI: Number,
    cntCAI: Number,
    cntAI: Number,
    cntHI: Number,
    cntRERA: Number,
    cntSNI: Number,
    cntBreath: Number,
    cntSelfBreath: Number,
    medPress: Number,
    medIPAP: Number,
    medEPAP: Number,
    medLEAK: Number,
    medVt: Number,
    medMV: Number,
    medRR: Number,
    medTi: Number,
    medIE: Number,
    p95Press: Number,
    p95IPAP: Number,
    p95EPAP: Number,
    p95LEAK: Number,
    p95Vt: Number,
    p95MV: Number,
    p95RR: Number,
    p95Ti: Number,
    p95IE: Number,
    maxPress: Number,
    maxIPAP: Number,
    maxEPAP: Number,
    maxLEAK: Number,
    maxVt: Number,
    maxMV: Number,
    maxRR: Number,
    maxTi: Number,
    maxIE: Number,
    maxSPO2: Number,
    minSPO2: Number,
    avgSPO2: Number,
    oxygenIndex: Number,
    actualTimeSPO2: Number,
    maxPR: Number,
    minPR: Number,
    avgPR: Number,
    aveDBP: Number,
    aveSBP: Number,
    hbpCounts: Number,
});
const partsSchema = new mongoose.Schema({
    component: String,
    lastChanged: String,
    frequency: Number,
    nextDue: String
})
const Usage = mongoose.model('Usage', usageSchema, 'usage')
const Parts = mongoose.model('Parts', partsSchema)
module.exports = { Usage, Parts };